function Hd = filtro
%FILTRO Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.10 and the Signal Processing Toolbox 6.13.
%
% Generated on: 12-May-2012 18:55:35
%

% FIR least-squares Bandstop filter designed using the FIRLS function.

% All frequency values are in Hz.
Fs = 7400;  % Sampling Frequency

N      = 12;    % Order
Fpass1 = 10;    % First Passband Frequency
Fstop1 = 34;    % First Stopband Frequency
Fstop2 = 38;    % Second Stopband Frequency
Fpass2 = 2000;  % Second Passband Frequency
Wpass1 = 100;   % First Passband Weight
Wstop  = 1;     % Stopband Weight
Wpass2 = 1;     % Second Passband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fpass1 Fstop1 Fstop2 Fpass2 Fs/2]/(Fs/2), [1 1 0 0 1 ...
           1], [Wpass1 Wstop Wpass2]);
Hd = dfilt.dffir(b);

% [EOF]
